[book]
authors = ["Trail of Bits"]
language = "en"
multilingual = false
src = "."
title = "Building Secure Contracts"
description = "This repository, brought to you by Trail of Bits, outlines our guidelines and best practices to write secure smart contracts."
logo = "static/TOB_Black.svg"

[output.html]
git-repository-url = "https://github.com/crytic/building-secure-contracts"
edit-url-template = "https://github.com/crytic/building-secure-contracts/edit/master/{path}"
cname = "crytic.github.io/building-secure-contracts"
no-section-label = true
additional-css = ["static/custom.css"]
additional-js = ["static/script.js"]
default-theme = "light"
mathjax-support = true

[output.html.fold]
enable = true
level = 1
