blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: mailto:opensource@trailofbits.com
    about: Please report security vulnerabilities via email, not as GitHub issues.
  - name: Questions
    url: https://slack.empirehacking.nyc/
    about: Ask questions in the #ethereum channel on Empire Hacking Slack.
